name: Verify CI

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  verify_valid:
    name: Verify valid image
    uses: PrintScript8/ingsis-library/.github/workflows/on-pull-request.yml@main

  publish_docker:
    name: Publish Docker image
    needs: verify_valid
    uses: PrintScript8/ingsis-library/.github/workflows/docker-image.yml@main
    with:
      service_name: ${{ github.ref == 'refs/heads/main' && 'snippet' || 'snippet-dev' }}

permissions:
  packages: write