name: Verify CI

on:
  push:
    branches:
      - 'main'

jobs:
  verify_valid:
    name: Verify valid image
    uses: PrintScript8/ingsis-library/blob/main/.github/workflows/on-pull-request.yml@main

  publish_docker:
    name: Publish Docker image
    needs: verify_valid
    uses: PrintScript8/ingsis-library/blob/main/.github/workflows/docker-image.yml@main
    with:
      service_name: 'snippet'
      run_docker_compose: true

permissions:
  packages: write